kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: arpgalaxy
    password: Arpgalaxy4316**
    repo: test
    tags: latest
    dockerfile: ./Dockerfile